"""Realized P&L checked against a hand calculation (LED-204).

samples/pnl_check_trades.csv holds the trades; samples/pnl_check_expected.csv is the FIFO
matching worked out by hand, one row per lot slice a sell consumes. The expected figures are
typed in, never generated by this codebase, so the check is independent of the code under test.
"""

import csv
from collections import Counter, defaultdict
from decimal import Decimal
from pathlib import Path

import pytest

SAMPLES = Path(__file__).parent.parent / "samples"
TRADES_CSV = SAMPLES / "pnl_check_trades.csv"
EXPECTED_CSV = SAMPLES / "pnl_check_expected.csv"
CENT = Decimal("0.01")


def read_rows(path: Path) -> list[dict[str, str]]:
    # DictReader yields one dict per row, keyed by the header (like a DataTable row by column)
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


@pytest.fixture(scope="module")  # read once for all tests in this file
def expected() -> list[dict[str, str]]:
    return read_rows(EXPECTED_CSV)


# --- The sample itself meets the story's criteria ---------------------------------------------


def test_sample_has_at_least_ten_trades():
    assert len(read_rows(TRADES_CSV)) >= 10


def test_sample_has_a_lot_closed_across_several_sells(expected):
    sells_per_lot = Counter((r["symbol"], r["lot_buy_date"]) for r in expected)
    assert max(sells_per_lot.values()) >= 2


def test_hand_calculation_rows_are_arithmetically_right(expected):
    # guards against a typo in the sheet: each slice is quantity x (sell - buy)
    for r in expected:
        qty, buy, sell = (Decimal(r[k]) for k in ("quantity", "buy_price", "sell_price"))
        assert Decimal(r["pnl"]) == qty * (sell - buy), r


# --- The API agrees with the hand calculation -------------------------------------------------


def test_api_realized_pnl_matches_hand_calculation_to_the_cent(client, expected):
    pid = client.post("/portfolios", json={"name": "P&L check"}).json()["id"]
    with TRADES_CSV.open("rb") as f:
        r = client.post(f"/portfolios/{pid}/trades", files={"file": ("trades.csv", f, "text/csv")})
    assert r.status_code == 201

    by_symbol: dict[str, Decimal] = defaultdict(Decimal)
    for row in expected:
        by_symbol[row["symbol"]] += Decimal(row["pnl"])

    body = client.get(f"/portfolios/{pid}/pnl").json()
    actual = {s["symbol"]: Decimal(s["realized_pnl"]) for s in body["symbols"]}

    assert actual.keys() == by_symbol.keys()  # AMD is never sold, so it isn't listed
    for symbol, want in by_symbol.items():
        assert actual[symbol].quantize(CENT) == want.quantize(CENT), symbol
    assert Decimal(body["total"]).quantize(CENT) == sum(by_symbol.values()).quantize(CENT)
